name: A workflow for my Hello World file
on : push
Jobs:
	build:
		Name: Hello world action
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v1
			- uses: ./action-a
				with:
					MY_NAME: “Vasanthi Rajkumar”
